### ISSUE TITLE
mountebank-maven-plugin:1.0-SNAPSHOT:stop fails on windows 7

### ISSUE THREAD

**Issue by ghost** [thejamesthomas/mountebank-maven-plugin#2]
Hello

This is a windows only error. Java 1.8 / mvn 3.3.3 / mountebank v1.3.0 (node v4.1.1)

Any help would be appreciated.

Thanks

Ajay

======

Error:
```
[INFO] --- mountebank-maven-plugin:1.0-SNAPSHOT:stop (Reset Mountebank) @ mock-api ---
[WARNING] The POM for org.mbtest.mountebank:mountebank-maven-plugin:jar:1.0-20160803.145832-1 is missing, no dependency information available
[INFO] Stopping Mountebank...
[INFO] Current OS is: Windows 7
[INFO] Command is: C:\tmp/mb.cmd
java.io.IOException: Cannot run program "C:\tmp/mb.cmd": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.mbtest.mountebank.system.ProcessBuilderWrapper.start(ProcessBuilderWrapper.java:10)
        at org.mbtest.mountebank.system.ProcessBuilderAdapter.start(ProcessBuilderAdapter.java:19)
        at org.mbtest.mountebank.Runner.run(Runner.java:30)
        at org.mbtest.mountebank.Runner.stopMountebank(Runner.java:26)
        at org.mbtest.mountebank.StopMojo.execute(StopMojo.java:16)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 27 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] reconconsole2-parent ............................... SUCCESS [  0.411 s]
[INFO] application ........................................ SUCCESS [  6.062 s]
[INFO] mock-api ........................................... FAILURE [  0.110 s]
[INFO] integration-tests .................................. SKIPPED
[INFO] functional-tests ................................... SKIPPED
[INFO] package ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.680 s
[INFO] Finished at: 2016-12-19T18:08:29-05:00
[INFO] Final Memory: 27M/554M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.mbtest.mountebank:mountebank-maven-plugin:1.0-SNAPSHOT:stop (Reset Mountebank) on project mock-api: Cannot run program "C:\tmp/mb.cmd": CreateProcess
error=2, The system cannot find the file specified -> [Help 1]
```

when running the MB with following config in pom.xml

```
        <plugin>
            <groupId>org.mbtest.mountebank</groupId>
            <artifactId>mountebank-maven-plugin</artifactId>
            <version>1.0-SNAPSHOT</version>
            <configuration>
                <mountebankFolder>${mountebank.Path}</mountebankFolder>
            </configuration>
            <executions>
                <execution>
                    <id>Reset Mountebank</id>
                    <phase>process-resources</phase>
                    <goals>
                        <goal>stop</goal>
                    </goals>
                </execution>
                <execution>
                    <id>Start Mountebank</id>
                    <phase>process-test-classes</phase>
                    <goals>
                        <goal>start</goal>
                    </goals>
                </execution>
                <execution>
                    <id>Stop Mountebank</id>
                    <phase>post-integration-test</phase>
                    <goals>
                        <goal>stop</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
```

**Comment by ghost** [comment]
Sorry. I had ${mountebank.Path} set incorrectly. This is not an issue.
